# Generated by Django 5.1.7 on 2025-03-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='backgroundImage',
        ),
    ]
