# Generated by Django 5.1.7 on 2025-03-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0002_delete_backgroundimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterQuickLink',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='price',
        ),
    ]
