# Generated by Django 5.1.7 on 2025-03-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0003_delete_footerquicklink_remove_schoolclass_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolfacility',
            name='background_color',
            field=models.CharField(choices=[('primary', 'Primary'), ('success', 'Success'), ('warning', 'Warning'), ('info', 'Info')], help_text='Background color for the facility item.', max_length=20),
        ),
    ]
