# Generated by Django 5.1.7 on 2025-03-29 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0004_alter_schoolfacility_background_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_popular', models.BooleanField(default=False, help_text='Marks whether the teacher is popular.')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webportal.teacher')),
            ],
        ),
    ]
