# Generated by Django 5.1.7 on 2025-03-29 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0005_popularteacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopularTeacher',
        ),
    ]
