# Generated by Django 5.1.7 on 2025-04-16 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0009_subject_alter_timetable_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='team_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='webportal.teammember'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='class_name',
            field=models.CharField(help_text="The name of the class (e.g., 'Class1,Class2')", max_length=255),
        ),
    ]
