# Generated by Django 5.1.7 on 2025-04-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0010_teacher_team_member_alter_schoolclass_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='team_member',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject_expert',
            field=models.ManyToManyField(blank=True, related_name='expert_teachers', to='webportal.subject'),
        ),
    ]
