# Generated by Django 5.1.7 on 2025-04-16 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0011_remove_teacher_team_member_teacher_subject_expert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='full_name',
        ),
        migrations.AddField(
            model_name='teammember',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='webportal.teacher'),
        ),
    ]
