# Generated by Django 5.1.7 on 2025-04-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0012_remove_teammember_full_name_teammember_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('roll_no', 'school_class')},
        ),
    ]
