# Generated by Django 5.1.7 on 2025-04-16 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0013_student_roll_no_alter_student_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='webportal.subject'),
        ),
    ]
