# Generated by Django 5.1.7 on 2025-04-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0014_homework_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.AddField(
            model_name='student',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
