# Generated by Django 5.1.7 on 2025-04-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0016_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='teacher',
        ),
    ]
