# Generated by Django 5.1.7 on 2025-04-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0017_remove_schoolclass_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='mobile',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
