# Generated by Django 5.1.7 on 2025-04-29 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0018_remove_teacher_user_teacher_email_teacher_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the syllabus section', max_length=255)),
                ('content', models.TextField(help_text='Detailed content of the syllabus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='webportal.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='webportal.teacher')),
            ],
            options={
                'verbose_name_plural': 'Syllabi',
                'unique_together': {('subject', 'title')},
            },
        ),
    ]
