# Generated by Django 5.1.7 on 2025-04-29 11:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0019_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Detailed content of the syllabus'),
        ),
    ]
