# Generated by Django 5.1.7 on 2025-05-03 09:47

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0019_teacher_user_alter_teacher_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='content',
            field=tinymce.models.HTMLField(help_text='Detailed content of the syllabus'),
        ),
    ]
