# Generated by Django 5.1.7 on 2025-05-17 10:09

import datetime
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0020_alter_syllabus_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name_plural': 'Homeworks'},
        ),
        migrations.AlterUniqueTogether(
            name='homework',
            unique_together={('subject', 'title')},
        ),
        migrations.AddField(
            model_name='homework',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='webportal.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homework',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pen_number',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homework',
            name='assigned_date',
            field=models.DateField(default=datetime.date.today, help_text='Date when the homework was assigned'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='No description provided.', help_text='Detailed description of the homework'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateField(default=datetime.date.today, help_text='Date when the homework is due'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='webportal.subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(default='Untitled Homework', help_text='Title of the homework', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='homework',
            name='school_class',
        ),
    ]
