# Generated by Django 5.1.7 on 2025-05-08 09:33

import datetime
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0020_alter_syllabus_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name_plural': 'Homeworks'},
        ),
        migrations.AlterUniqueTogether(
            name='homework',
            unique_together={('subject', 'title')},
        ),
        migrations.AddField(
            model_name='homework',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='webportal.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homework',
            name='title',
            field=models.CharField(default='Untitled Homework', help_text='Title of the homework', max_length=255),
        ),
        migrations.AddField(
            model_name='homework',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='assigned_date',
            field=models.DateField(default=datetime.date.today, help_text='Date when the homework was assigned'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='No description provided.', help_text='Detailed description of the homework'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateField(default=datetime.date.today, help_text='Date when the homework is due'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='webportal.subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='homework',
            name='school_class',
        ),
    ]
