# Generated by Django 5.1.7 on 2025-05-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0021_alter_homework_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
