# Generated by Django 5.1.7 on 2025-05-20 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0022_alter_timetable_options_timetable_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_for', to='webportal.teacher'),
        ),
    ]
