# Generated by Django 5.1.7 on 2025-06-14 09:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0025_alter_homework_unique_together_remove_homework_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='time',
        ),
        migrations.CreateModel(
            name='StudentDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(help_text='Title or subject of the diary entry', max_length=255)),
                ('entry', models.TextField(help_text='Diary entry or note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='webportal.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_entries', to='webportal.teacher')),
            ],
            options={
                'verbose_name_plural': 'Student Diaries',
                'ordering': ['-date', 'student'],
            },
        ),
    ]
