# Generated by Django 5.1.7 on 2025-05-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0026_alter_student_phone_no_alter_student_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pen_number',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
    ]
