# Generated by Django 5.1.7 on 2025-07-07 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webportal', '0026_remove_schoolclass_time_studentdiary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_point', models.CharField(max_length=100)),
                ('end_point', models.CharField(max_length=100)),
                ('stops', models.TextField(help_text='Comma-separated list of stops')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('bus', 'Bus'), ('van', 'Van'), ('car', 'Car'), ('other', 'Other')], max_length=10)),
                ('capacity', models.PositiveIntegerField()),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_contact', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_point', models.CharField(max_length=100)),
                ('drop_point', models.CharField(max_length=100)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TMS.route')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webportal.student')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TMS.vehicle')),
            ],
        ),
    ]
