# Generated by Django 5.1.7 on 2025-07-07 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0001_initial'),
        ('webportal', '0026_remove_schoolclass_time_studentdiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportassignment',
            name='school_class',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webportal.schoolclass'),
            preserve_default=False,
        ),
    ]
