# Generated by Django 5.1.7 on 2025-07-09 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0001_initial'),
        ('webportal', '0026_remove_schoolclass_time_studentdiary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='driver_contact',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='driver_name',
        ),
        migrations.AddField(
            model_name='transportassignment',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webportal.schoolclass'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TMS.driver'),
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('start_meter_value', models.PositiveIntegerField(help_text='Odometer reading when taking the vehicle')),
                ('start_time', models.DateTimeField(blank=True, help_text='Time when vehicle was taken', null=True)),
                ('end_meter_value', models.PositiveIntegerField(blank=True, help_text='Odometer reading when returning the vehicle', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='Time when vehicle was returned', null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TMS.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TMS.vehicle')),
            ],
        ),
    ]
