# Generated by Django 5.1.7 on 2025-07-09 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0002_driver_remove_vehicle_driver_contact_and_more'),
        ('webportal', '0026_remove_schoolclass_time_studentdiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportassignment',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webportal.schoolclass'),
        ),
    ]
